### ISSUE TITLE
Unnecessary Javascript could be done with CSS

### ISSUE THREAD

**Issue by ngyikp** [zerobase/fb_hide_like_notifs#2]
Instead of bundling jQuery and running Javascript every 0.1 seconds just to hide like notifications, it could be done with this CSS:

``` css
._33c[data-gt*='"notif_type":"like"'] {display:none !important;}
```
